### ISSUE TITLE
Workshop path is wrong when having Steam and game installed in different locations

### ISSUE THREAD

**Issue by Crynano** [NBKRedSpy/QM-BepInExCompatibility#1]
I have Steam installed in my C:\ drive.
I have Quasimorph installed in my D:\ drive.

Workshop files for the game are located in the same drive the game is installed, not steam install location.
Thus when recovering install location from registry, the final workshop path differs for me, and throws an exception.

![image](https://github.com/NBKRedSpy/QM-BepInExCompatibility/assets/174223393/c5ff3347-751f-45fa-b30e-1482e2d3e507)
![image](https://github.com/NBKRedSpy/QM-BepInExCompatibility/assets/174223393/33a98847-6834-496d-80d1-d65efb380953)
![image](https://github.com/NBKRedSpy/QM-BepInExCompatibility/assets/174223393/747ad64e-22b5-45ac-aaaa-a7ad110e2146)

**Comment by NBKRedSpy** [comment]
Version 1.1 has the ability to add the workshop for the library in the config.
This is a hack.  I think the info is in the library.vdf.

The challenge is getting a parser that actually works with the mono libraries installed in Quasimorph.

**Comment by NBKRedSpy** [comment]
Addressed with the 1.2.0
